// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using knowledge_sharing_platform_cloud.Data.Models;

#nullable disable

namespace knowledge_sharing_platform_cloud.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250407104629_KnowledgeFierceDBMigrations")]
    partial class KnowledgeFierceDBMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("knowledge_sharing_platform_cloud.Data.Models.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR(50)")
                        .HasColumnName("category_name");

                    b.Property<long>("ChannelId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("channel_id");

                    b.Property<bool>("MemberPrivilege")
                        .HasColumnType("bit")
                        .HasColumnName("member_privilege");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("knowledge_sharing_platform_cloud.Data.Models.Channel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 21000L);

                    b.Property<DateTime?>("ActiveTime")
                        .HasColumnType("DATETIME")
                        .HasColumnName("active_time");

                    b.Property<string>("ChannelImgBackground")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("channel_img_background");

                    b.Property<string>("ChannelImgUrl")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("channel_img_url");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasColumnName("created_time")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<long?>("LastPostId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("last_post_id");

                    b.Property<string>("StripePriceId")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("stripe_price_id");

                    b.Property<decimal?>("SubscriptionFee")
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("subscription_fee");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR(30)")
                        .HasColumnName("topic");

                    b.Property<int>("TotalMember")
                        .HasColumnType("INT")
                        .HasColumnName("total_member");

                    b.Property<int>("TotalPost")
                        .HasColumnType("INT")
                        .HasColumnName("total_post");

                    b.Property<long>("UserId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Channel");
                });

            modelBuilder.Entity("knowledge_sharing_platform_cloud.Data.Models.ChannelMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ChannelId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("channel_id");

                    b.Property<decimal?>("SubscriptionFeePaid")
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("subscription_fee_paid");

                    b.Property<long>("UserId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("UserId");

                    b.ToTable("Channel_Member");
                });

            modelBuilder.Entity("knowledge_sharing_platform_cloud.Data.Models.Comment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CommentContent")
                        .HasColumnType("TEXT")
                        .HasColumnName("comment_content");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasColumnName("created_time")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<long>("ParentId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("parent_id");

                    b.Property<long>("PostId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("post_id");

                    b.Property<long>("RootId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("root_id");

                    b.Property<long>("UserId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("knowledge_sharing_platform_cloud.Data.Models.Likes", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 61000L);

                    b.Property<bool>("LikeStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("like_status");

                    b.Property<long>("PostId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("post_id");

                    b.Property<long>("UserId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId", "PostId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Likes_UserId_PostId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("knowledge_sharing_platform_cloud.Data.Models.Post", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 51000L);

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("body");

                    b.Property<long>("CategoryId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasColumnName("created_time")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("DeletedStatus")
                        .HasColumnType("bit")
                        .HasColumnName("deleted_status");

                    b.Property<string>("PostImgUrl")
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("post_img_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasColumnName("updated_time")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<long>("UserId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("knowledge_sharing_platform_cloud.Data.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 11000L);

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasColumnName("created_time")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("NVARCHAR(320)")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("password");

                    b.Property<string>("ProfileUrl")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("profile_url");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("salt");

                    b.Property<string>("StripeAccountId")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("stripe_account_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR(20)")
                        .HasColumnName("username");

                    b.Property<string>("WebPushSubscription")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("web_push_subscription");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_User_Email");

                    b.ToTable("User");
                });

            modelBuilder.Entity("knowledge_sharing_platform_cloud.Data.Models.Category", b =>
                {
                    b.HasOne("knowledge_sharing_platform_cloud.Data.Models.Channel", null)
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("knowledge_sharing_platform_cloud.Data.Models.Channel", b =>
                {
                    b.HasOne("knowledge_sharing_platform_cloud.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("knowledge_sharing_platform_cloud.Data.Models.ChannelMember", b =>
                {
                    b.HasOne("knowledge_sharing_platform_cloud.Data.Models.Channel", null)
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("knowledge_sharing_platform_cloud.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("knowledge_sharing_platform_cloud.Data.Models.Comment", b =>
                {
                    b.HasOne("knowledge_sharing_platform_cloud.Data.Models.Post", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("knowledge_sharing_platform_cloud.Data.Models.Likes", b =>
                {
                    b.HasOne("knowledge_sharing_platform_cloud.Data.Models.Post", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("knowledge_sharing_platform_cloud.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("knowledge_sharing_platform_cloud.Data.Models.Post", b =>
                {
                    b.HasOne("knowledge_sharing_platform_cloud.Data.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("knowledge_sharing_platform_cloud.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
